version: '3'

services:
    database:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        depends_on:
            -   database
        environment:
            ADMINER_DEFAULT_DB_DRIVER: pqsql
            ADMINER_DEFAULT_DB_HOST: postgres
            ADMINER_DEFAULT_DB_NAME: main
        ports:
            - 8080:8080

    redis:
        image: redis:5-alpine
        ports: [6379]

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    blackfire:
        image: blackfire/blackfire
        env_file: .env.local
        ports: [8707]